"use client"

import { Button } from "@/components/ui/button"
import { Printer } from "lucide-react"

type ReportRow = { label: string; value: string; bold?: boolean }

function esc(value: string) {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}

function buildReportHtml(title: string, dateLabel: string, sections: { heading: string; rows: ReportRow[] }[]) {
  const sectionHtml = sections.map((section) => {
    const rows = section.rows.map((r) =>
      `<tr${r.bold ? ' style="font-weight:bold;background:#f5f5f5"' : ""}><td style="padding:6px 0">${esc(r.label)}</td><td style="text-align:right;padding:6px 0">${esc(r.value)}</td></tr>`
    ).join("")
    return `<h2 style="font-size:16px;margin:18px 0 6px;border-bottom:1px solid #ddd;padding-bottom:4px">${esc(section.heading)}</h2><table style="width:100%;border-collapse:collapse">${rows}</table>`
  }).join("")

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  body{font-family:monospace;max-width:480px;margin:0 auto;padding:20px;color:#000;font-size:15px}
  h1{text-align:center;font-size:22px;margin:0 0 4px}
  .sub{text-align:center;font-size:14px;color:#666;margin-bottom:16px}
  hr{border:0;border-top:1px dashed #999;margin:12px 0}
  .footer{text-align:center;margin-top:24px;font-size:13px;color:#666}
  @media print{body{padding:0;font-size:14px}}
</style></head><body>
<h1>JIRANI SHOP SYSTEM</h1>
<div class="sub">${esc(title)} &bull; ${esc(dateLabel)}</div>
<hr>
${sectionHtml}
<hr>
<div class="footer">Generated by JIRANI SHOP SYSTEM</div>
</body></html>`
}

export function ReportPrint({ title, dateLabel, salesRows, collectionRows, accountingRows }: {
  title: string
  dateLabel: string
  salesRows: ReportRow[]
  collectionRows: ReportRow[]
  accountingRows: ReportRow[]
}) {
  function handlePrint() {
    const html = buildReportHtml(title, dateLabel, [
      { heading: "Sales", rows: salesRows },
      { heading: "Collections", rows: collectionRows },
      { heading: "Accounting", rows: accountingRows },
    ])
    const blob = new Blob([html], { type: "text/html" })
    const url = URL.createObjectURL(blob)
    const win = window.open(url, "_blank", "noopener,noreferrer,width=520,height=700")
    if (win) {
      win.addEventListener("load", () => {
        URL.revokeObjectURL(url)
        try { win.print() } catch {}
      })
    } else {
      URL.revokeObjectURL(url)
    }
  }

  return (
    <Button variant="outline" size="sm" onClick={handlePrint}>
      <Printer className="size-4" /> Print report
    </Button>
  )
}
