"use client"

import { useMemo, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { toast } from "sonner"
import { adjustInventory, createProduct, createSupplier, updateProduct } from "@/app/actions/inventory"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Badge } from "@/components/ui/badge"
import { formatKES } from "@/lib/format"
import { Loader2, Package, Plus, Minus, X, Search, MessageCircle, Smartphone, Pencil } from "lucide-react"

type Supplier = { id: string; name: string; phone: string | null; notes: string | null }
type Product = { id: string; name: string; brand: string | null; sku: string | null; cost_price: number; selling_price: number; quantity: number; reorder_level: number; supplier_id: string | null; suppliers: Supplier | null }

export function InventoryClient({ products, suppliers: initialSuppliers }: { products: Product[]; suppliers: Supplier[] }) {
  const router = useRouter(); const [pending, startTransition] = useTransition()
  const [productsState, setProductsState] = useState(products); const [suppliers, setSuppliers] = useState(initialSuppliers)
  const [selected, setSelected] = useState<Product | null>(null); const [editing, setEditing] = useState<Product | null>(null); const [showForm, setShowForm] = useState(false); const [showSupplierForm, setShowSupplierForm] = useState(false)
  const [search, setSearch] = useState(""); const [amount, setAmount] = useState(1); const [note, setNote] = useState("")
  const filtered = useMemo(() => { const q = search.trim().toLowerCase(); if (!q) return productsState; return productsState.filter((p) => [p.name, p.brand, p.sku, p.suppliers?.name, p.suppliers?.phone].some((value) => value?.toLowerCase().includes(q))) }, [productsState, search])
  function submit(direction: 1 | -1) { if (!selected) return; startTransition(async () => { const result = await adjustInventory({ productId: selected.id, quantity: direction * Math.max(1, Math.floor(amount)), note }); if ("error" in result) { toast.error(result.error); return }; toast.success(`Stock updated to ${result.quantity}`); setSelected(null); setNote(""); setProductsState((current) => current.map((p) => p.id === selected.id ? { ...p, quantity: result.quantity ?? p.quantity } : p)); router.refresh() }) }
  function addProduct(formData: FormData) { startTransition(async () => { const result = await createProduct({ name: String(formData.get("name") || ""), brand: String(formData.get("brand") || ""), sku: String(formData.get("sku") || ""), costPrice: Number(formData.get("cost_price")), sellingPrice: Number(formData.get("selling_price")), quantity: Number(formData.get("quantity")), reorderLevel: Number(formData.get("reorder_level")) }); if ("error" in result) { toast.error(result.error); return }; toast.success("Product added to inventory"); setShowForm(false); router.refresh() }) }
  function saveProduct(formData: FormData) { if (!editing) return; startTransition(async () => { const result = await updateProduct({ productId: editing.id, name: String(formData.get("name") || ""), brand: String(formData.get("brand") || ""), sku: String(formData.get("sku") || ""), costPrice: Number(formData.get("cost_price")), sellingPrice: Number(formData.get("selling_price")), reorderLevel: Number(formData.get("reorder_level")), supplierId: String(formData.get("supplier_id") || "") || null }); if ("error" in result) { toast.error(result.error); return }; setProductsState((current) => current.map((product) => product.id === result.productId ? { ...product, ...result.product } : product)); toast.success("Product details updated"); setEditing(null); router.refresh() }) }
  function saveSupplier(formData: FormData) { startTransition(async () => { const result = await createSupplier({ name: String(formData.get("supplier_name") || ""), phone: String(formData.get("supplier_phone") || ""), notes: String(formData.get("supplier_notes") || "") }); if ("error" in result) { toast.error(result.error); return }; if (result.supplier) setSuppliers((current) => [...current, result.supplier].sort((a, b) => a.name.localeCompare(b.name))); setShowSupplierForm(false); toast.success("Supplier added") }) }
  function contactUrl(product: Product, mode: "whatsapp" | "sms") { const phone = product.suppliers?.phone?.replace(/[^0-9+]/g, "").replace(/^\+/, ""); const message = `Hello ${product.suppliers?.name || "supplier"}, please restock ${product.name}${product.sku ? ` (SKU: ${product.sku})` : ""}.`; return mode === "whatsapp" ? `https://wa.me/${phone}?text=${encodeURIComponent(message)}` : `sms:${phone}?body=${encodeURIComponent(message)}` }
  return <div className="flex flex-col gap-4">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="sr-only">Inventory</h1><p className="text-sm text-muted-foreground">Add products, monitor stock, and preserve every adjustment in the audit trail.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => setShowSupplierForm((v) => !v)}>{showSupplierForm ? <X data-icon="inline-start" /> : <Plus data-icon="inline-start" />} Supplier</Button><Button onClick={() => setShowForm((v) => !v)}>{showForm ? <X data-icon="inline-start" /> : <Plus data-icon="inline-start" />} {showForm ? "Close" : "Add product"}</Button></div></div>
    <div className="relative"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name, brand, SKU, or supplier" aria-label="Search inventory" /></div>
    {showSupplierForm && <Card><CardHeader><CardTitle>Add supplier</CardTitle></CardHeader><CardContent><form action={saveSupplier} className="grid gap-4 sm:grid-cols-3"><div className="grid gap-1.5"><Label htmlFor="supplier_name">Supplier name *</Label><Input id="supplier_name" name="supplier_name" required /></div><div className="grid gap-1.5"><Label htmlFor="supplier_phone">Phone / WhatsApp</Label><Input id="supplier_phone" name="supplier_phone" placeholder="+254..." /></div><div className="grid gap-1.5"><Label htmlFor="supplier_notes">Notes</Label><Input id="supplier_notes" name="supplier_notes" /></div><div className="sm:col-span-3 flex justify-end"><Button type="submit" disabled={pending}>{pending && <Loader2 data-icon="inline-start" className="animate-spin" />} Save supplier</Button></div></form></CardContent></Card>}
    {showForm && <Card><CardHeader><CardTitle>Add product</CardTitle></CardHeader><CardContent><form action={addProduct} className="grid gap-4 sm:grid-cols-2"><div className="grid gap-1.5 sm:col-span-2"><Label htmlFor="name">Product name *</Label><Input id="name" name="name" required minLength={2} /></div><div className="grid gap-1.5"><Label htmlFor="brand">Brand</Label><Input id="brand" name="brand" /></div><div className="grid gap-1.5"><Label htmlFor="sku">SKU</Label><Input id="sku" name="sku" /></div><div className="grid gap-1.5"><Label htmlFor="cost_price">Cost price (KES) *</Label><Input id="cost_price" name="cost_price" type="number" min="0" step="0.01" required /></div><div className="grid gap-1.5"><Label htmlFor="selling_price">Selling price (KES) *</Label><Input id="selling_price" name="selling_price" type="number" min="0" step="0.01" required /></div><div className="grid gap-1.5"><Label htmlFor="quantity">Initial stock *</Label><Input id="quantity" name="quantity" type="number" min="0" step="1" defaultValue="0" required /></div><div className="grid gap-1.5"><Label htmlFor="reorder_level">Reorder level *</Label><Input id="reorder_level" name="reorder_level" type="number" min="0" step="1" defaultValue="5" required /></div><div className="flex justify-end sm:col-span-2"><Button type="submit" disabled={pending}>{pending && <Loader2 data-icon="inline-start" className="animate-spin" />} Save product</Button></div></form></CardContent></Card>}
    {editing && <Card className="border-primary/40"><CardHeader><CardTitle className="flex items-center justify-between">Edit product <Button variant="ghost" size="sm" onClick={() => setEditing(null)}>Cancel</Button></CardTitle></CardHeader><CardContent><form action={saveProduct} className="grid gap-4 sm:grid-cols-2"><div className="grid gap-1.5 sm:col-span-2"><Label htmlFor="edit-name">Product name *</Label><Input id="edit-name" name="name" defaultValue={editing.name} required /></div><div className="grid gap-1.5"><Label htmlFor="edit-brand">Brand</Label><Input id="edit-brand" name="brand" defaultValue={editing.brand || ""} /></div><div className="grid gap-1.5"><Label htmlFor="edit-sku">SKU</Label><Input id="edit-sku" name="sku" defaultValue={editing.sku || ""} /></div><div className="grid gap-1.5"><Label htmlFor="edit-cost">Cost price</Label><Input id="edit-cost" name="cost_price" type="number" min="0" step="0.01" defaultValue={editing.cost_price} required /></div><div className="grid gap-1.5"><Label htmlFor="edit-selling">Selling price</Label><Input id="edit-selling" name="selling_price" type="number" min="0" step="0.01" defaultValue={editing.selling_price} required /></div><div className="grid gap-1.5"><Label htmlFor="edit-reorder">Reorder level</Label><Input id="edit-reorder" name="reorder_level" type="number" min="0" step="1" defaultValue={editing.reorder_level} required /></div><div className="grid gap-1.5"><Label htmlFor="edit-supplier">Supplier</Label><select id="edit-supplier" name="supplier_id" defaultValue={editing.supplier_id || ""} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="">No supplier</option>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="flex justify-end sm:col-span-2"><Button type="submit" disabled={pending}>{pending && <Loader2 data-icon="inline-start" className="animate-spin" />} Save changes</Button></div></form></CardContent></Card>}
    {selected && <Card className="border-primary/40"><CardHeader><CardTitle className="flex items-center justify-between">Adjust stock <Button variant="ghost" size="sm" onClick={() => setSelected(null)}>Cancel</Button></CardTitle></CardHeader><CardContent className="grid gap-3 sm:grid-cols-[1fr_auto_auto]"><div><p className="text-sm font-medium">{selected.name}</p><p className="text-xs text-muted-foreground">Current: {selected.quantity} units</p></div><Input type="number" min={1} value={amount} onChange={(e) => setAmount(Number(e.target.value))} /><div className="flex gap-2"><Button disabled={pending} onClick={() => submit(1)}><Plus data-icon="inline-start" /> Add</Button><Button disabled={pending} variant="outline" onClick={() => submit(-1)}><Minus data-icon="inline-start" /> Remove</Button></div><Input className="sm:col-span-3" placeholder="Reason or supplier note (optional)" value={note} onChange={(e) => setNote(e.target.value)} /></CardContent></Card>}
    {(() => { const outOfStock = productsState.filter((product) => product.quantity === 0); const lowStock = productsState.filter((product) => product.quantity > 0 && product.quantity <= product.reorder_level); return <Card className="border-amber-500/30"><CardHeader><CardTitle className="flex items-center justify-between">Stock alerts <span className="text-sm font-normal text-muted-foreground">{outOfStock.length + lowStock.length} products need attention</span></CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2"><Badge variant="destructive">{outOfStock.length} out of stock</Badge><Badge variant="secondary">{lowStock.length} low stock</Badge>{outOfStock.length === 0 && lowStock.length === 0 && <span className="text-sm text-muted-foreground">All products are above their reorder levels.</span>}</div></CardContent></Card> })()}
    <Card><CardHeader><CardTitle>Stock levels <span className="text-sm font-normal text-muted-foreground">({filtered.length})</span></CardTitle></CardHeader><CardContent className="p-0"><div className="divide-y divide-border">{filtered.length === 0 && <p className="p-6 text-center text-sm text-muted-foreground">No matching products.</p>}{filtered.map((product) => { const low = product.quantity <= product.reorder_level; const supplier = product.suppliers; return <div key={product.id} className="flex flex-col gap-3 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 items-center gap-3"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-accent text-accent-foreground"><Package /></span><div className="min-w-0"><p className="truncate text-sm font-medium">{product.name}</p><p className="truncate text-xs text-muted-foreground">{product.brand || product.sku || "No SKU"} · {formatKES(Number(product.selling_price))}{supplier ? ` · ${supplier.name}` : ""}</p></div></div><div className="flex flex-wrap items-center gap-2"><Badge variant={product.quantity === 0 ? "destructive" : low ? "secondary" : "outline"}>{product.quantity} units</Badge><Button size="sm" variant="outline" onClick={() => setEditing(product)}><Pencil data-icon="inline-start" /> Edit</Button><Button size="sm" variant="outline" onClick={() => setSelected(product)}>Adjust</Button>{product.quantity === 0 && supplier?.phone && <><Button size="sm" variant="outline" asChild><a href={contactUrl(product, "whatsapp")} target="_blank" rel="noreferrer"><MessageCircle data-icon="inline-start" /> WhatsApp</a></Button><Button size="sm" variant="outline" asChild><a href={contactUrl(product, "sms")}><Smartphone data-icon="inline-start" /> SMS</a></Button></>}</div></div> })}</div></CardContent></Card>
  </div>
}
